org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
neoforge_version=26.2.0.64
#neogradle.subsystems.decompiler.enabled=false
jei_verid=8685162
cloth_config=8269700
sodium=8396429
carry_on_id=4882500
player_animation_lib=1.0.2-rc1+1.20
create_version = 0.5.1.j-55
flywheel_version = 0.6.11-13
registrate_version = MC1.20-1.3.3
rhino_version=2001.2.3-build.6
architectury_version=9.2.14
kubejs_version=2001.6.5-build.14